### ISSUE TITLE
panic in lambda/logserver/logserver.go

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-lambda-extension#267]
We observed a panic from this extension in our Lambda function logs.

We are using `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicLambdaExtension:39`.

It panicked here: https://github.com/newrelic/newrelic-lambda-extension/blob/e00e3cdb78c372d3376d52fbc3b19cd893caf426/lambda/logserver/logserver.go#L172

The specific panic was `send on closed channel`.

**Comment by chaudharysaket** [comment]
Hi @rittneje 
We can see that the latest layer as seen [here](https://layers.newrelic-external.com/)  is `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicLambdaExtension:46`
Could you please let us know if you face the same issue with the latest layer and, if possible, share the scenario leading to it?
Thank you!

**Comment by rittneje** [comment]
@chaudharysaket We don't know what led to it. All we see is a few minutes after the previous START/REPORT/END, the very next thing is a stack trace from this extension crashing.

```
[NR_EXT] http: panic serving 169.254.79.129:40200: send on closed channel
goroutine 38 [running]:
net/http.(*conn).serve.func1()
/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/server.go:1854 +0xbf
panic({0x983be0, 0xce39c0})
/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:890 +0x263
github.com/newrelic/newrelic-lambda-extension/lambda/logserver.(*LogServer).handler(0xc00040ae00, {0xceac80, 0xc00068a460}, 0xc000385100)
/home/runner/work/newrelic-lambda-extension/newrelic-lambda-extension/lambda/logserver/logserver.go:172 +0xaf7
net/http.HandlerFunc.ServeHTTP(0xc00068a460?, {0xceac80?, 0xc00068a460?}, 0xa499d3?)
/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xceac80, 0xc00068a460}, 0xc000385100)
/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xce9ae8?}, {0xceac80, 0xc00068a460}, 0xc000385100)
/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0003098c0, {0xceaf38, 0xc000532990})
/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/server.go:3089 +0x5ed
```

**Comment by chaudharysaket** [comment]
Hi @rittneje 
As mentioned above, please use latest layer - `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicLambdaExtension:46` as seen [here](https://layers.newrelic-external.com/).
As noted in the Extension [v2.3.11](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.11) release notes, we fixed crashing on closed pipe. We will re-look into closing of channels for logs to see if there is no additional edge case resulting in crashing of Extension.
Thank you!

**Comment by n-osanai** [comment]
@chaudharysaket 

The same issue is still occurring. I'm using the following Lambda layer: 
`arn:aws:lambda:ap-northeast-1:451483290750:layer:NewRelicPython312:29` which should include Extension version v2.3.11 or later.
Here are the logs around the panic:

```
...
2025-04-11T01:14:07.324Z [NR_EXT] mainLoop: waiting for next lambda invocation event...
2025-04-11T01:14:07.324Z END RequestId: 3a26744c-9c45-57cc-a2f9-143ef35d6d5c
2025-04-11T01:14:07.324Z REPORT RequestId: 3a26744c-9c45-57cc-a2f9-143ef35d6d5c Duration: 1921.39 ms Billed Duration: 1922 ms Memory Size: 128 MB Max Memory Used: 114 MB Init Duration: 1602.11 ms
2025-04-11T01:19:54.729Z [NR_EXT] Telemetry client error: failed to send data within user defined timeout period: 30s, payload size: 5005 bytes
2025-04-11T01:19:54.729Z [NR_EXT] sendPayloads: took 5m47.516063653s to finish sending all payloads
2025-04-11T01:19:54.729Z [NR_EXT] Sent 0/1 New Relic function log batches successfully with certainty in 347516.707ms (347516ms to transmit 0.0kB).
2025-04-11T01:19:54.750Z [NR_EXT] New Relic Extension shutting down after 2 events
2025-04-11T01:19:54.769Z [NR_EXT] attemptSend: timeout error, retrying after 200.000067ms: Post "https://log-api.newrelic.com/log/v1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2025-04-11T01:19:54.770Z [NR_EXT] Log server terminating: http: Server closed
2025-04-11T01:19:54.770Z [NR_EXT] Formatted Return Report: Duration: 1921.39 ms Billed Duration: 1922 ms Memory Size: 128 MB Max Memory Used: 114 MB Init Duration: 1602.11 ms
2025-04-11T01:19:54.771Z [NR_EXT] http: panic serving 169.254.79.129:38740: send on closed channel
2025-04-11T01:19:54.771Z goroutine 47 [running]:
2025-04-11T01:19:54.771Z net/http.(*conn).serve.func1()
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/net/http/server.go:1947 +0xbe
2025-04-11T01:19:54.771Z panic({0x9ee700?, 0xccdf90?})
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/runtime/panic.go:785 +0x132
2025-04-11T01:19:54.771Z github.com/newrelic/newrelic-lambda-extension/lambda/logserver.(*LogServer).handler(0xc0005d41c0, {0xcd65f0, 0xc0003b00e0}, 0xc0000d03c0?)
2025-04-11T01:19:54.771Z /home/runner/work/newrelic-lambda-extension/newrelic-lambda-extension/lambda/logserver/logserver.go:172 +0xb9e
2025-04-11T01:19:54.771Z net/http.HandlerFunc.ServeHTTP(0xc0003b0000?, {0xcd65f0?, 0xc0003b00e0?}, 0x0?)
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/net/http/server.go:2220 +0x29
2025-04-11T01:19:54.771Z net/http.(*ServeMux).ServeHTTP(0x40ef85?, {0xcd65f0, 0xc0003b00e0}, 0xc0000d03c0)
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/net/http/server.go:2747 +0x1ca
2025-04-11T01:19:54.771Z net/http.serverHandler.ServeHTTP({0xcd2650?}, {0xcd65f0?, 0xc0003b00e0?}, 0x6?)
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/net/http/server.go:3210 +0x8e
2025-04-11T01:19:54.771Z net/http.(*conn).serve(0xc0003c25a0, {0xcd6c18, 0xc0008449c0})
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/net/http/server.go:2092 +0x5d0
2025-04-11T01:19:54.771Z created by net/http.(*Server).Serve in goroutine 13
2025-04-11T01:19:54.771Z /opt/hostedtoolcache/go/1.23.6/x64/src/net/http/server.go:3360 +0x485
2025-04-11T01:19:54.771Z [NR_EXT] Aggressive harvest yielded 0 invocations
2025-04-11T01:19:54.771Z [NR_EXT] Waiting for background tasks to complete
2025-04-11T01:19:54.771Z [NR_EXT] Extension shutdown after 350871ms
```
Let me know if you need any additional context.

**Comment by chaudharysaket** [comment]
We will release Extension `v2.3.20` with the logserver changes by end of this week or beginning of next week. Thank you!

**Comment by n-osanai** [comment]
@chaudharysaket 
Thank you for your quick response.
I tried using the newly released version, but it seems that [Python Agent v10.12.0.1](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v10.12.0.1_python) includes Extension v2.3.19, not v2.3.20 as expected.
Could you please confirm this?
