### ISSUE TITLE
Layer Errors prevent the "main" Lambda to get executed

### ISSUE THREAD

**Issue by ftieben** [newrelic/newrelic-lambda-extension#65]
## Description
We recently instrumented all our node.js Lambdas with the NR Layer and noticed by an accident (wrong VPC Config for one Lambda), that if the  NR Collector could not be reached in 5.0 Seconds, the "main" Lambda is not being executed. This will add a hard dependency to NewRelic in our Setup. 

## Steps to Reproduce
Create a Lambda in a private VPC which can not reach the NR Collector

## Expected Behaviour
Just log the timeout and execute the "main" Lambda

## Relevant Logs / Console output

```
timestamp,message
1617087177609,"[NR_EXT] New Relic Lambda Extension starting up
1617087187732,"START RequestId: 26922b09-3892-472f-b30e-040960748b43 Version: $LATEST
1617087188692,"[NR_EXT] New Relic Lambda Extension starting up
1617087190735,"EXTENSION	Name: newrelic-lambda-extension	State: Registered	Events: [INVOKE,SHUTDOWN]
1617087192737,"END RequestId: 26922b09-3892-472f-b30e-040960748b43
1617087192737,"REPORT RequestId: 26922b09-3892-472f-b30e-040960748b43	Duration: 5004.28 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 28 MB	
1617087192737,"2021-03-30T06:53:12.736Z 26922b09-3892-472f-b30e-040960748b43 Task timed out after 5.00 seconds
```

**Comment by kolanos** [comment]
@ftieben Thanks for reporting this issue. Transferred it to the relevant repository.

**Comment by darrensmithwtc** [comment]
Hi

Just to add to the above, we suffered an outage in production last night for a number of lambdas due to this as well I believe, but it was due to the cloud-collectors in EU failing, as opposed to connectivity failure during VPC!


&nbsp; | 2021-05-18T02:29:24.456+01:00 | START RequestId: 83c5dbdc-4872-4bc5-9a99-b606fbe9a70a Version: $LATEST
-- | -- | --
&nbsp; | 2021-05-18T02:29:31.279+01:00 | [NR_EXT] Request failed. Ran out of retries after 3 attempts.
&nbsp; | 2021-05-18T02:29:31.279+01:00 | [NR_EXT] Telemetry client error: Post "https://cloud-collector.eu01.nr-data.net/aws/lambda/v1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
&nbsp; | 2021-05-18T02:29:31.279+01:00 | [NR_EXT] Sent 0/1 New Relic payload batches with 1 log events successfully in 6020.657ms (6000ms to transmit 0.0kB).
&nbsp; | 2021-05-18T02:29:31.280+01:00 | END RequestId: 83c5dbdc-4872-4bc5-9a99-b606fbe9a70a


Is there a workaround we can put in for now to stop this happening until a proper fix is available? Reducing the timeout or whatever for the NR_EXT? I cannot have a repeat of production outage due to API failure NR side.

Thanks

**Comment by kolanos** [comment]
@ftieben Thanks for the update. We have released a refactor of our timeout logic which should (hopefully) do the right thing in most cases. We  hope you'll give it a try and report any issues you run into. In this specific use case, the extension should no longer suffer from a runaway HTTP request and will instead exit within the deadlines provided by Lambda.

**Comment by ftieben** [comment]
@kolanos Thanks a lot for the work you are doing, I've tried an example Lambda with the new Layer Version

`arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicNodeJS12X:44`

The Lambda is working fine while it can reach NR but it is still failing as soon as I put it into an VPC without allowed egress:

Response:

Response
```json
{
  "errorMessage": "2021-06-04T06:59:10.097Z 72f018d0-250d-4326-86e6-6e3b4b1e3c49 Task timed out after 5.00 seconds"
}
```

Logs:
```
START RequestId: 72f018d0-250d-4326-86e6-6e3b4b1e3c49 Version: $LATEST
[NR_EXT] New Relic Lambda Extension starting up
EXTENSION	Name: newrelic-lambda-extension	State: Registered	Events: [INVOKE,SHUTDOWN]
END RequestId: 72f018d0-250d-4326-86e6-6e3b4b1e3c49
REPORT RequestId: 72f018d0-250d-4326-86e6-6e3b4b1e3c49	Duration: 5004.30 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 32 MB	
2021-06-04T06:59:10.097Z 72f018d0-250d-4326-86e6-6e3b4b1e3c49 Task timed out after 5.00 seconds
```

**Comment by kolanos** [comment]
@ftieben Thanks for the udpate. What is the timeout configured for the function? And are you reproting to the New Relic EU region? Going to try to reproduce this as closely as I can. Any other details that might be relevant would be useful as well.

**Comment by kolanos** [comment]
@ftieben I was able to reproduce and subsequently simulate this issue. Have a pull request in the works (#75), should be merged and released early next week.

**Comment by kolanos** [comment]
@ftieben We have released the deadline tweaks in #75. Hope you'll give it a try and report any issues. Thanks again.

**Comment by kolanos** [comment]
@ftieben Closing this for now. Please feel free to re-open if you continue to have issues. Am reasonably confident this case is now handled gracefully by the extension. Thanks again.
